### ISSUE TITLE
Theme flickering when opening workspace

### ISSUE THREAD

**Issue by bitstrider** [blueneogeo/workspace-theme#2]
When opening a workspace with a theme assigned, the editor does not immediately load the theme. There's a short delay, during which the default theme is used.

This doesn't really affect the functionality of extension overall, and is more of a quirk in the experience.

**Comment by blueneogeo** [comment]
Hi bitstrider. Glad you are enjoying the extension. 

The only thing the workspace-theme extension really does is set the theme in your workspace settings, when you use the menu, using the existing workspace theme feature in VSCode. It is not involved in loading your editors. The behavior you see is simply how VSCode loads. You may want to open a ticket there.
